service: ab-test-demo
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  deploymentMethod: direct
plugins:
  - '@silvermine/serverless-plugin-cloudfront-lambda-edge'
  - serverless-s3-sync
custom:
  s3Sync:
    - bucketName: ab-test-demo-website-bucket
      localDir: website
      deleteRemoved: true
functions:
  abTestRequest:
    handler: ab-test-request.handler
    memorySize: 128
    timeout: 5
    lambdaAtEdge:
        eventType: viewer-request
        distribution: CloudFrontDistribution
  abTestResponse:
    handler: ab-test-response.handler
    memorySize: 128
    timeout: 5
    lambdaAtEdge:
        eventType: viewer-response
        distribution: CloudFrontDistribution
resources:
  Resources:
    WebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ab-test-demo-website-bucket
        WebsiteConfiguration:
          IndexDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    WebsiteBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref WebsiteBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - s3:GetObject
              Effect: Allow
              Principal: '*'
              Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
            OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf # CORS-S3Origin
            AllowedMethods:
              - HEAD
              - GET
              - OPTIONS
          Origins:
          - Id: S3Origin
            DomainName: !Select [1, !Split ["//", !GetAtt WebsiteBucket.WebsiteURL]]
            CustomOriginConfig:
              OriginProtocolPolicy: 'http-only'
  Outputs:
    ABTestURL:
      Value: !Sub 'https://${CloudFrontDistribution.DomainName}/code-like-leonardo/'
